- hosts: client
  become: true
  become_method: sudo
  become_user: root
  vars_prompt:
    - name: "client_public_IP"
      prompt: "Enter Client Public IP "
      private: no

    - name: "namenode_public_IP"
      prompt: "Enter Namenode Public IP "
      private: no

    - name: "namenode_port"
      prompt: "Enter namenode port "
      private: no

  tasks: 
    - name: "downloading jdk"
      get_url:
       url: http://35.244.242.82/yum/java/el7/x86_64/jdk-8u171-linux-x64.rpm
       dest: /home/ec2-user/jdk-8u171-linux-x64.rpm
       mode: '0644'
    
    - name: "checking the jdk installed or not"
      shell: "java -version"
      register: java_result
      ignore_errors: yes
    - debug:
       var: java_result

    - name: "installing jdk"
      shell: "rpm -i jdk-8u171-linux-x64.rpm"
      when: java_result.rc==127 
  
    - name: "downloading hadoop"
      get_url:
       url: https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
       dest: /home/ec2-user/hadoop-1.2.1-1.x86_64.rpm
       mode: '0644'

    - name: "checking the hadoop installed or not"
      shell: "hadoop -version"
      ignore_errors: yes
      register: hadoop_result
    - debug:
       var: hadoop_result

    - name: "installing hadoop"
      shell: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
      when: hadoop_result.rc==127 

    - name: "copying core file to client"
      template:
       src: "C_core-site.xml"
       dest: "/etc/hadoop/core-site.xml"

    - name: "checking status of connection"
      shell: "hadoop dfsadmin -report"
      register: client_connect
    - debug:
       var: client_connect.stdout

  
    
